### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-graphql-explorer#129]
It's not possible to install depdencies, when running `yarn install`, the following error occurs:

```
error babel-jest@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.4.0"
error Found incompatible module.
```

**Comment by emmenko** [comment]
Make sure to have the correct node version running in your shell.

**Comment by ahmehri** [comment]
@emmenko I was using the right node version as indicated in the `.nvmrc` file.

I retested this morning and the problem is gone now that Yarn v3 is being used.
